# https://hub.docker.com/_/microsoft-dotnet-sdk
FROM mcr.microsoft.com/dotnet/sdk:6.0

# set the working directory
WORKDIR /app

# for installing dependencies
COPY *.csproj ./
# pull down dependencies/dependencies
RUN dotnet restore

COPY . ./

# what we want to run
#ENTRYPOINT [ "dotnet", "watch", "run" ]
ENTRYPOINT dotnet watch run --no-restore