name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # - name: Pull changes from remote
      #   run: |
      #     git pull origin master
      
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          # Repository name with owner. For example, actions/checkout
          repository: 'rawan-a-d/configuration'
          # The branch, tag or SHA to checkout. When checking out the repository that triggered a workflow, this defaults to the reference or SHA for that event.  Otherwise, uses the default branch.
  
          token: ${{ secrets.GH_TOKEN }}
          
      - name: Update Client yaml file in place
        # You may pin to the exact commit or the version.
        uses: loveholidays/gitops-action-yaml-updater@v1.0.0
        with:
          # TYPE of the new value to be updated
          mode: IMAGE_TAG
          # Name of the container
          container-name: auth
          # Path to the yaml file
          filepath: K8S/auth-depl.yaml
          # Tag value for the new image
          new-image-tag: ${{ github.sha }}
          
      - name: Add & Commit
        # You may pin to the exact commit or the version.
        uses: EndBug/add-and-commit@v9.0.0
        with:
          # Arguments for the git add command
          add: "*"
          # The message for the commit
          message: Update docker image version
          # pull: '--rebase --autostash'
          # Whether to push the commit and, if any, its tags to the repo. It can also be used to set the git push arguments (more info in the README)
          push: true
          # The token used to make requests to the GitHub API. It's NOT used to make commits and should not be changed.
          github_token: ${{ secrets.GH_TOKEN }}
      - name: Pull changes again (to make sure local changes are up-to-date)
        run: |
          echo ${{ github.sha }}
          git pull origin master

      - name: GitHub Push
        # You may pin to the exact commit or the version.
        uses: ad-m/github-push-action@v0.6.0
        with:
          # Token for the repo. Can be passed in using $\{{ secrets.GITHUB_TOKEN }}
          github_token: ${{ secrets.GH_TOKEN }}
          repository: 'rawan-a-d/configuration'
          # Destination branch to push changes
          branch: master
          # Determines if force push is used
          force: false
